# Generated by Django 6.0 on 2025-12-05 12:55

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to=catalog.models.product_image_upload_path),
        ),
        migrations.AlterField(
            model_name='products',
            name='article',
            field=models.PositiveIntegerField(default=398546451, unique=True),
        ),
    ]
