# Generated by Django 6.0 on 2025-12-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_images_image_alter_products_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='article',
            field=models.PositiveIntegerField(default=178724591, unique=True),
        ),
    ]
