# Generated by Django 6.0 on 2025-12-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_products_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='article',
            field=models.PositiveIntegerField(default=910863431, unique=True),
        ),
    ]
