# Generated by Django 6.0 on 2025-12-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_products_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='article',
            field=models.PositiveIntegerField(default=65432487, unique=True),
        ),
    ]
